name: Deploy-Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
    VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
          
      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy API to Vercel
        run: |
          vercel --prod --token $VERCEL_TOKEN --confirm
