name: deploy-route-optimization

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  S3_BUCKET: route-optimization-bucket
  PACKAGE_DIR: my_lambda_package

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Create package directory
        run: mkdir ${{ env.PACKAGE_DIR }}

      - name: Install dependencies
        run: pip install -r requirements.txt -t ${{ env.PACKAGE_DIR }}

      - name: Add Python scripts to the package directory
        run: |
          cp lambda_function.py ${{ env.PACKAGE_DIR }}
          cp RoutesGenerator.py ${{ env.PACKAGE_DIR }}

      - name: List package directory contents
        run: ls -l ${{ env.PACKAGE_DIR }}

      - name: Zip the package
        run: zip -r ${{ env.PACKAGE_DIR }}.zip ${{ env.PACKAGE_DIR }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Upload to S3
        run: aws s3 cp ${{ env.PACKAGE_DIR }}.zip s3://${{ env.S3_BUCKET }}/${{ env.PACKAGE_DIR }}.zip
